# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buku.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbuku.proto\x12\x04\x62uku\"f\n\x04\x42uku\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x06 \x01(\t\x12\r\n\x05stock\x18\x07 \x01(\x05\"\x11\n\x0f\x42ukuListRequest\"-\n\x10\x42ukuListResponse\x12\x19\n\x05\x62ukus\x18\x01 \x03(\x0b\x32\n.buku.Buku\"\x19\n\x0b\x42ukuRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x0c\x42ukuResponse\x12\x18\n\x04\x62uku\x18\x01 \x01(\x0b\x32\n.buku.Buku\"g\n\x11\x42ukuCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\r\n\x05stock\x18\x05 \x01(\x05\".\n\x12\x42ukuCreateResponse\x12\x18\n\x04\x62uku\x18\x01 \x01(\x0b\x32\n.buku.Buku\"s\n\x11\x42ukuUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\".\n\x12\x42ukuUpdateResponse\x12\x18\n\x04\x62uku\x18\x01 \x01(\x0b\x32\n.buku.Buku\"\x1f\n\x11\x42ukuDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x42ukuDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa9\x02\n\x0b\x42ukuService\x12\x35\n\x04List\x12\x15.buku.BukuListRequest\x1a\x16.buku.BukuListResponse\x12,\n\x03Get\x12\x11.buku.BukuRequest\x1a\x12.buku.BukuResponse\x12;\n\x06\x43reate\x12\x17.buku.BukuCreateRequest\x1a\x18.buku.BukuCreateResponse\x12;\n\x06Update\x12\x17.buku.BukuUpdateRequest\x1a\x18.buku.BukuUpdateResponse\x12;\n\x06\x44\x65lete\x12\x17.buku.BukuDeleteRequest\x1a\x18.buku.BukuDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buku_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUKU']._serialized_start=20
  _globals['_BUKU']._serialized_end=122
  _globals['_BUKULISTREQUEST']._serialized_start=124
  _globals['_BUKULISTREQUEST']._serialized_end=141
  _globals['_BUKULISTRESPONSE']._serialized_start=143
  _globals['_BUKULISTRESPONSE']._serialized_end=188
  _globals['_BUKUREQUEST']._serialized_start=190
  _globals['_BUKUREQUEST']._serialized_end=215
  _globals['_BUKURESPONSE']._serialized_start=217
  _globals['_BUKURESPONSE']._serialized_end=257
  _globals['_BUKUCREATEREQUEST']._serialized_start=259
  _globals['_BUKUCREATEREQUEST']._serialized_end=362
  _globals['_BUKUCREATERESPONSE']._serialized_start=364
  _globals['_BUKUCREATERESPONSE']._serialized_end=410
  _globals['_BUKUUPDATEREQUEST']._serialized_start=412
  _globals['_BUKUUPDATEREQUEST']._serialized_end=527
  _globals['_BUKUUPDATERESPONSE']._serialized_start=529
  _globals['_BUKUUPDATERESPONSE']._serialized_end=575
  _globals['_BUKUDELETEREQUEST']._serialized_start=577
  _globals['_BUKUDELETEREQUEST']._serialized_end=608
  _globals['_BUKUDELETERESPONSE']._serialized_start=610
  _globals['_BUKUDELETERESPONSE']._serialized_end=647
  _globals['_BUKUSERVICE']._serialized_start=650
  _globals['_BUKUSERVICE']._serialized_end=947
# @@protoc_insertion_point(module_scope)
